FROM golang:1.24-alpine

RUN apk add --no-cache ffmpeg
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go install github.com/air-verse/air@latest
EXPOSE 5000
RUN mkdir -p uploads
CMD ["air"]